# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/" # Location of package manifests
    schedule:
      interval: "monthly"

  # Don't version packages explicitly, let the resolver do it
  #
  # - package-ecosystem: "julia"
  #   directories: # Location of Julia projects
  #     - "/"
  #   schedule:
  #     interval: "daily"
  #   groups:
  #     # Group all Julia package updates into a single PR:
  #     all-julia-packages:
  #       patterns:
  #         - "*"
  #   ignore:
  #     # broken AD
  #     - dependency-name: "Turing"
  #       versions: [ ">=0.46" ]
  #     - dependency-name: "DynamicPPL"
  #       versions: [ ">=0.42" ]
